# Generated by Django 4.2.24 on 2025-09-17 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zeitlabs_payments_cart',
            },
        ),
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('paid_course', 'Paid Course')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'zeitlabs_payments_catalogueitem',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('gateway', models.CharField(max_length=50)),
                ('gateway_transaction_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fake_models.cart')),
            ],
            options={
                'db_table': 'zeitlabs_payments_transaction',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='fake_models.cart')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fake_models.transaction')),
            ],
            options={
                'db_table': 'zeitlabs_payments_invoice',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fake_models.cart')),
                ('catalogue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fake_models.catalogueitem')),
            ],
            options={
                'db_table': 'zeitlabs_payments_cartitem',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('gateway', models.CharField(blank=True, max_length=50, null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='fake_models.cart')),
            ],
            options={
                'db_table': 'zeitlabs_payments_auditlog',
            },
        ),
    ]
